version: '3.8'

services:
  #service 1. database PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: datawarehouse
      POSTGRES_USER: spark_user
      POSTGRES_PASSWORD: spark_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #Airflow Webserver
  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: airflow_webserver
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://spark_user:spark_password@postgres:5432/datawarehouse
      - AIRFLOW__WEBSERVER__SECRET_KEY=CANTIK
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8888:8080"
    command: webserver
    depends_on:
      - postgres

  #Airflow Scheduler
  aiflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow_scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://spark_user:spark_password@postgres:5432/datawarehouse
      - AIRFLOW__WEBSERVER__SECRET_KEY=CANTIK
    volumes:
      - ./dags:/opt/airflow/dags
      - //var/run/docker.sock:/var/run/docker.sock
    command: scheduler
    depends_on:
      - postgres

  #service 2. Aplikasi pyspark
  pyspark-app:
    build: .
    container_name: pyspark_runner
    depends_on:
      - postgres

volumes:
  postgres_data: 
